### ISSUE TITLE
Is this project still being used and maintained?

### ISSUE THREAD

**Issue by philipschm1tt** [ConnectedHomes/sqs-kafka-connect#1]
Hi @skate056 ,

We appreciate you building this open-source.
We are considering using this connector, but we are a bit hesitant, since the connector is still using Kafka 0.10.2 and we don’t know if it will ever be upgraded or maintained in the future. Since we have no experience with Scala, it seems risky to use the connector – for example if there are ever breaking changes for SQS.

What are your plans for the connector?

Thanks,
Philip

**Comment by skate056** [comment]
Hi @maeh2k,

Thanks for your interest. We had built this connector for one of our jobs to land data into Kafka. We don't use that job anymore so this has not been updated to the latest version of Kafka. I'll try to get this upgraded.

Thanks,
Saket

**Comment by philipschm1tt** [comment]
Thank you.
We’ll give the connector a try.

**Comment by skate056** [comment]
The connector has been upgraded to use Kafka 1.1.1 and has been tested with Confluent platform 5.0
