### ISSUE TITLE
Cannot use a region other than eu-west-1

### ISSUE THREAD

**Issue by jutley** [ConnectedHomes/sqs-kafka-connect#4]
While there is a configuration parameter for eu-west-1, it does not work.

This is because the `toMap` function of the `Conf` case class does not include the region. This means that when it is converted to a Map, then back into a Conf within the Task, it will default to eu-west-1.

https://github.com/ConnectedHomes/sqs-kafka-connect/blob/master/src/main/scala/com/hivehome/kafka/connect/sqs/Conf.scala#L30-L38

**Comment by skate056** [comment]
Fixed #3
