### ISSUE TITLE
Cannot use AWS credentials other than Key/Secret

### ISSUE THREAD

**Issue by jutley** [ConnectedHomes/sqs-kafka-connect#5]
We'd like to be able to use roles to handle AWS auth, but the app currently forces us to use an access key and secret. The default provider chain will do this properly, and it should be used when we do not provide an access key and secret, but currently we cannot create a new connector without specifying an access key/secret.

This can be fixed by providing defaults for these configs, and filtering them out if they are the defaults.

**Comment by skate056** [comment]
Fixed #3
